package errcode

var (
	ERRNoTable          = NewErr(10001, "the table of the service has not been created")
	ERRCreateTable      = NewErr(10002, "can not create table of the service")
	ERRCreateData       = NewErr(10003, "create data failed")
	ERRUpdateData       = NewErr(10004, "update data failed")
	ERRDeleteData       = NewErr(10005, "delete data failed")
	ERRFindData         = NewErr(10006, "find data failed")
	ERRCount            = NewErr(10007, "count data failed")
	ERRFindQueryIsEmpty = NewErr(10008, "find query is empty")
	ERRSetKV            = NewErr(10009, "set k-v in cache failed")
	ERRAddSet           = NewErr(10010, "sadd val in cache failed")
	ERRGetKV            = NewErr(10011, "get k-v from cache failed")
	ERRConvertJson      = NewErr(10012, "convert json failed")
	ERRGetSet           = NewErr(10013, "get set from cache failed")
	ERRNoRightRecord    = NewErr(10014, "no right  record found")
	ERRCacheMiss        = NewErr(10015, "cache miss")
	ERRUpdateQueryEmpty = NewErr(10016, "update query is empty")
)
